version: '3'
services:
  authority0:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/authority0.toml
      --ws-interface 0.0.0.0
      --unsafe-expose   
      --jsonrpc-cors all
    volumes:
      - ./parity/config:/parity/config
      - ./parity/authorities/chaindata/0:/root/.local/share/io.parity.ethereum/
      - ./parity/authorities/authority0.json:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}/authority.json
      - ./parity/keys:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}
      - ./parity/authorities/authority0.pwd:/parity/authorities/authority0.pwd
      - ./parity/node0.network.key:/root/.local/share/io.parity.ethereum/network/key
    ports:
      - 8545:8545
    networks:
      app_net:
        ipv4_address: 172.16.0.10


  authority1:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/authority1.toml
    volumes:
      - ./parity/config:/parity/config
      - ./parity/authorities/chaindata/1:/root/.local/share/io.parity.ethereum/
      - ./parity/authorities/authority1.json:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}/authority.json
      - ./parity/authorities/authority1.pwd:/parity/authorities/authority1.pwd
      - ./parity/node1.network.key:/root/.local/share/io.parity.ethereum/network/key
    ports:
      - 8544:8545
    networks:
      app_net:
        ipv4_address: 172.16.0.11


  authority2:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/authority2.toml
    volumes:
      - ./parity/config:/parity/config
      - ./parity/authorities/chaindata/2:/root/.local/share/io.parity.ethereum/
      - ./parity/authorities/authority2.json:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}/authority.json
      - ./parity/authorities/authority2.pwd:/parity/authorities/authority2.pwd
      - ./parity/node2.network.key:/root/.local/share/io.parity.ethereum/network/key
    ports:
      - 8543:8545
    networks:
      app_net:
        ipv4_address: 172.16.0.12

  member0:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/member.toml
      --ws-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config
      - ./parity/keys:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}
    ports:
      - 9180:8180
      - 9546:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.20


  member1:
    image: parity/parity:${PARITY_VERSION}
    command: --config /parity/config/member.toml
    volumes:
      - ./parity/config:/parity/config
    networks:
      app_net:
        ipv4_address: 172.16.0.21


  member2:
    image: parity/parity:${PARITY_VERSION}
    command: --config /parity/config/member.toml
    volumes:
      - ./parity/config:/parity/config
    networks:
      app_net:
        ipv4_address: 172.16.0.22


  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json
    networks:
      app_net:
        ipv4_address: 172.16.0.100

  secret0:
    image: kryha/parity-secretstore
    command:
      --config /parity/config/secret/ss0.toml
      --ws-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config
    ports:
      - 7010:8010
      - 7545:8545
    networks: 
      app_net:
          ipv4_address: 172.16.0.30

  secret1:
    image: kryha/parity-secretstore
    command:
      --config /parity/config/secret/ss1.toml
      --ws-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config
    networks: 
      app_net:
          ipv4_address: 172.16.0.31

  secret2:
    image: kryha/parity-secretstore
    command:
      --config /parity/config/secret/ss2.toml
      --ws-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config
    networks: 
      app_net:
          ipv4_address: 172.16.0.32


  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json
    ports:
      - 3001:3000
    networks:
      app_net:
        ipv4_address: 172.16.0.200

networks:
  app_net:
      ipam:
        driver: default
        config:
            - subnet: 172.16.0.1/24