version: '3'
services:
  
  member0:
    image: parity/parity:beta
    command:
      --config /parity/config/users.toml
      --dapps-interface 0.0.0.0
      --ws-interface 0.0.0.0
      --ui-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config:ro
    ports:
      - 8180:8180
      - 8546:8545


  member1:
    image: parity/parity:beta
    command: --config /parity/config/users.toml
    volumes:
      - ./parity/config:/parity/config:ro


  member2:
    image: parity/parity:beta
    command: --config /parity/config/users.toml
    volumes:
      - ./parity/config:/parity/config:ro

  secret1:
    image: kryha/parity-secretstore
    command:
      --config /parity/config/secret/ss1.toml
      --ws-interface 0.0.0.0
      --ui-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config
    ports:
      - 8010:8010
      - 8545:8545

  secret2:
    image: kryha/parity-secretstore
    command:
      --config /parity/config/secret/ss2.toml
      --ws-interface 0.0.0.0
      --ui-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config

  secret3:
    image: kryha/parity-secretstore
    command:
      --config /parity/config/secret/ss3.toml
      --ws-interface 0.0.0.0
      --ui-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config

      
  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro

  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 3001:3000

