version: '3'
services:
  
  member0:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/member.toml
      --dapps-interface 0.0.0.0
      --ws-interface 0.0.0.0
      --ui-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config:ro
      - ./parity/keys:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}
    ports:
      - 8180:8180
      - 8546:8546
      - 30303:30303


  member1:
    image: parity/parity:${PARITY_VERSION}
    command: --config /parity/config/member.toml
    volumes:
      - ./parity/config:/parity/config:ro


  member2:
    image: parity/parity:${PARITY_VERSION}
    command: --config /parity/config/member.toml
    volumes:
      - ./parity/config:/parity/config:ro

  secret1:
    image: kryha/parity-secretstore
    command:
      --config /parity/config/secret/ss1.toml
    volumes:
      - ./parity/config:/parity/config

  secret2:
    image: kryha/parity-secretstore
    command:
      --config /parity/config/secret/ss2.toml
    volumes:
      - ./parity/config:/parity/config

  secret3:
    image: kryha/parity-secretstore
    command:
      --config /parity/config/secret/ss3.toml
    volumes:
      - ./parity/config:/parity/config

  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro

  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 3001:3000

