# Alice's config file in alice.toml

[parity]
chain = "dev"
base_path = "/parity/config/db.alice"

[rpc]
port = 8545 #default http port for RPC
apis = ["secretstore","eth","net","private","parity", "parity_accounts", "personal", "rpc"]    #add "private","parity","personal"
cors = ["all"]                                # allow remix to access this node

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["http://localhost:3000", "http://localhost:8080"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]

[secretstore]
disable = true # users do not run a secret store node

[private_tx]
enabled = true                                              # Enable private transactions.
#account = accountx      # Alice's account to sign requests sent to the Secret Store.
#signer = accountx
passwords = "/parity/config/secret/alice.pwd"                                     # File containing the password to unlock Alice accounts (signer, private account, validators).
sstore_url = "http://10.1.0.21:8010"                        # Specify secret store URL used for encrypting private transactions.

[account] # unlock Alice's account to deploy the contract
#unlock = [accountx]
password = ["/parity/config/secret/alice.pwd"]

[network]
port = 30303
#bootnodes = ["enode://ss1E","enode://ss2E","enode://ss3E",bobE,charlieE]
